version: '4.2'

services:
  postgres:
    image: postgres
    container_name: bd
    restart: always
    environment:
      POSTGRES_DB: $(DB_NAME)
      POSTGRES_USER: $(USERNAME)
      POSTGRES_PASSWORD: $(PASSWORD)
    ports:
      - "5432:5432"
  server:
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
