version: '4.2'

services:
  postgres:
    image: postgres
    container_name: bd
    restart: always
    environment:
      POSTGRES_DB: $(DB_NAME)
      POSTGRES_USER: $(USER)
      POSTGRES_PASSWORD: $(PASSWORD)
    ports:
      - "5432:5432"
