version: '2'  # Используйте совместимую версию Docker Compose

services:
  postgres:
    image: postgres:15.2
    container_name: postgres
    hostname: postgres
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_DB: postgres #
  #     POSTGRES_USER: postgres #
  #     POSTGRES_PASSWORD: postgres #
  #   ports:
  #     - "5432:5432"

  # cached_db:
  #   image: redis
  #   restart: always
  #   ports:
  #     - "6379:6379"

  # server:
  #   build: .
  #   command: uvicorn app.app:app --host 0.0.0.0 --port 8000
  #   environment:
  #     DB_NAME: postgres # ${DB_NAME}
  #     SECRET_KEY: ${SECRET_KEY}
  #     USER: postgres #${USER}
  #     PASSWORD: postgres #${PASSWORD}
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db
  #     # - postgres
  #     # - redis
  #   ports:
  #     - "8000:8000"
