"""upd db 

Revision ID: 0a83a32f6461
Revises: 27c17751c80b
Create Date: 2023-08-24 02:19:35.911718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a83a32f6461'
down_revision = '27c17751c80b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
