"""upd db async

Revision ID: 05fe951fc35e
Revises: 0a83a32f6461
Create Date: 2023-08-24 03:56:19.172634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05fe951fc35e'
down_revision = '0a83a32f6461'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
